# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bary_sinkhorn_arma <- function(weights, frechet, maxIter, lambda, C, thresh, threads) {
    .Call('_WSGeometry_bary_sinkhorn_arma', PACKAGE = 'WSGeometry', weights, frechet, maxIter, lambda, C, thresh, threads)
}

rand_cxx <- function() {
    .Call('_WSGeometry_rand_cxx', PACKAGE = 'WSGeometry')
}

index_cxx <- function(x, y) {
    .Call('_WSGeometry_index_cxx', PACKAGE = 'WSGeometry', x, y)
}

norm <- function(x, y) {
    .Call('_WSGeometry_norm', PACKAGE = 'WSGeometry', x, y)
}

expo <- function(a) {
    .Call('_WSGeometry_expo', PACKAGE = 'WSGeometry', a)
}

gen_cost <- function(A, B) {
    .Call('_WSGeometry_gen_cost', PACKAGE = 'WSGeometry', A, B)
}

wsbary_cxx_armaP <- function(weightsR, positions1, positionssetR, frechet_weights, fixed_support, maxIter, weights_maxIter, pos_maxIter, stepsize, thresh, headstart, headstartlength, threads) {
    .Call('_WSGeometry_wsbary_cxx_armaP', PACKAGE = 'WSGeometry', weightsR, positions1, positionssetR, frechet_weights, fixed_support, maxIter, weights_maxIter, pos_maxIter, stepsize, thresh, headstart, headstartlength, threads)
}

krbary_subgrad_cxx <- function(weightsR, costMatsR, frechet_weights, maxIter, stepsize, thresh, headstart, headstartlength, threads) {
    .Call('_WSGeometry_krbary_subgrad_cxx', PACKAGE = 'WSGeometry', weightsR, costMatsR, frechet_weights, maxIter, stepsize, thresh, headstart, headstartlength, threads)
}

maaipm_fixed_cpp <- function(p, s, x, b, costvec, constMat, N, m, M, sizes, sizescsum, nr, nc, U, maxIter, thresh, threads) {
    .Call('_WSGeometry_maaipm_fixed_cpp', PACKAGE = 'WSGeometry', p, s, x, b, costvec, constMat, N, m, M, sizes, sizescsum, nr, nc, U, maxIter, thresh, threads)
}

maaipm_free_cpp <- function(p, s, x, b, costvec, support, fullsupport, constMat, N, m, M, sizes, sizescsum, nr, nc, U, maxIter, outer_maxIter, thresh, threads) {
    .Call('_WSGeometry_maaipm_free_cpp', PACKAGE = 'WSGeometry', p, s, x, b, costvec, support, fullsupport, constMat, N, m, M, sizes, sizescsum, nr, nc, U, maxIter, outer_maxIter, thresh, threads)
}

transport_network_dual_arma <- function(a, b, C) {
    .Call('_WSGeometry_transport_network_dual_arma', PACKAGE = 'WSGeometry', a, b, C)
}

transport_network_primal_arma <- function(a, b, C) {
    .Call('_WSGeometry_transport_network_primal_arma', PACKAGE = 'WSGeometry', a, b, C)
}

umaaipm_free_cpp <- function(p, s, x, b, costvec, support, fullsupport, constMat, N, m, M, sizes, sizescsum, nr, nc, U, C, maxIter, outer_maxIter, thresh, threads) {
    .Call('_WSGeometry_umaaipm_free_cpp', PACKAGE = 'WSGeometry', p, s, x, b, costvec, support, fullsupport, constMat, N, m, M, sizes, sizescsum, nr, nc, U, C, maxIter, outer_maxIter, thresh, threads)
}

umaaipm_fixed_cpp <- function(p, s, x, b, costvec, support, fullsupport, constMat, N, m, M, sizes, sizescsum, nr, nc, U, C, maxIter, thresh, threads) {
    .Call('_WSGeometry_umaaipm_fixed_cpp', PACKAGE = 'WSGeometry', p, s, x, b, costvec, support, fullsupport, constMat, N, m, M, sizes, sizescsum, nr, nc, U, C, maxIter, thresh, threads)
}

